In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB


In [2]:
df = pd.read_csv('Boller_All.csv')
df.head()

Player       Span  Mat  Inns   Overs  Mdns  Runs  Wkts    Ave  Econ  \
0  Abdur Razzak  2004-2014  153   152  1327.3    70  6065   207  29.29  4.56   
1    Abul Hasan  2012-2018    7     7    36.0     1   244     0   0.00  6.77   
2     Abu Hider  2018-2018    2     2    18.0     2    89     3  29.66  4.94   
3     Abu Jayed  2019-2019    2     2    18.0     0   114     5  22.80  6.33   
4  Afif Hossain  2020-2020    1     1     2.0     0    12     1  12.00  6.00   

     SR  4  5  Ct  St        rat  res  
0  38.4  5  4  32   0  41.350027    1  
1   0.0  0  0   1   0  34.884921    0  
2  36.0  0  0   1   0  46.144819    1  
3  21.6  0  1   0   0  59.543860    1  
4  12.0  0  0   0   0  13.083333    0

In [3]:
df.describe()

Mat        Inns        Overs        Mdns         Runs  \
count   96.000000   96.000000    96.000000   96.000000    96.000000   
mean    33.333333   23.385417   167.107292    8.208333   835.166667   
std     48.729688   39.467340   321.166014   18.440754  1530.439639   
min      1.000000    1.000000     0.100000    0.000000     4.000000   
25%      3.750000    2.000000    10.750000    0.000000    66.750000   
50%     14.000000    7.000000    42.800000    1.000000   255.500000   
75%     41.000000   28.500000   170.050000    7.000000   921.000000   
max    218.000000  218.000000  1804.300000  122.000000  8785.000000   

             Wkts         Ave       Econ          SR          4          5  \
count   96.000000   96.000000  96.000000   96.000000  96.000000  96.000000   
mean    22.968750   32.624271   5.953125   38.911458   0.604167   0.197917   
std     47.579618   25.164953   3.182610   31.210170   1.497220   0.719938   
min      0.000000    0.000000   3.160000    0.000000   0.000000   0.000000   
25%      1.000000   14.850000   4.695000   19.200000   0.000000   0.000000   
50%      6.000000   32.755000   5.175000   38.550000   0.000000   0.000000   
75%     22.000000   44.850000   5.985000   52.800000   0.250000   0.000000   
max    269.000000  142.000000  26.000000  175.000000   8.000000   5.000000   

             Ct    St        rat        res  
count  96.00000  96.0  96.000000  96.000000  
mean    8.68750   0.0  31.544460   0.447917  
std    13.52449   0.0  12.064753   0.499890  
min     0.00000   0.0   4.000000   0.000000  
25%     1.00000   0.0  23.289084   0.000000  
50%     3.00000   0.0  33.834499   0.000000  
75%     8.25000   0.0  40.890843   1.000000  
max    64.00000   0.0  59.543860   1.000000

In [4]:
df['rating'] = df['Runs'] / df['Inns'] + df['Runs'] / df['BF'] + df['hundred'] + df['fifty'] / df['Inns'] + df['four']*4 / df['Inns']

In [5]:
df['rating'] = df['Runs'] / df['Inns'] + df['Runs'] / df['BF'] + df['hundred'] + df['fifty'] / df['Inns'] + df['four']*4 / df['Inns'] + df['six']*6 / df['Inns']+ df['zero']/ df['Inns']

In [7]:
df.head()

Player       Span  Mat  Inns  NO  Runs  HS    Ave    BF      SR  \
0  Abdur Razzak  2004-2014  153    97  39   779  53  13.43  1020   76.37   
1    Abul Hasan  2012-2018    7     3   0    11   7   3.66    16   68.75   
2     Abu Hider  2018-2018    2     1   0     1   1   1.00    11    9.09   
3  Afif Hossain  2020-2020    1     1   0     7   7   7.00     4  175.00   
4   Aftab Ahmed  2004-2010   85    85   6  1954  92  24.73  2353   83.04   

   hundred  fifty  zero  four  six     rating  
0        0      1    12    55   21  12.495684  
1        0      0     0     1    0   5.687500  
2        0      0     0     0    0   1.090909  
3        0      0     0     1    0  12.750000  
4        0     14     8   205   49  37.183370

In [8]:
df['res'] = df['rating'].apply(lambda x: '1' if x >= 20 else '0')

In [32]:
df.head()

Player       Span  Mat  Inns   Overs  Mdns  Runs  Wkts    Ave  Econ  \
0  Abdur Razzak  2004-2014  153   152  1327.3    70  6065   207  29.29  4.56   
1    Abul Hasan  2012-2018    7     7    36.0     1   244     0   0.00  6.77   
2     Abu Hider  2018-2018    2     2    18.0     2    89     3  29.66  4.94   
3     Abu Jayed  2019-2019    2     2    18.0     0   114     5  22.80  6.33   
4  Afif Hossain  2020-2020    1     1     2.0     0    12     1  12.00  6.00   

     SR  4  5  Ct  St        rat  res  
0  38.4  5  4  32   0  41.350027    1  
1   0.0  0  0   1   0  34.884921    0  
2  36.0  0  0   1   0  46.144819    1  
3  21.6  0  1   0   0  59.543860    1  
4  12.0  0  0   0   0  13.083333    0

In [4]:
target=df.res
inputs=df.drop(['res','Player','Span','rat'],axis='columns')

In [5]:
X_train, X_test, y_train, y_test= train_test_split(inputs,target,test_size=0.3)

In [6]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)

In [7]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [8]:
model.score(X_test, y_test)

0.7931034482758621

In [9]:
y_test[:5]

8     0
36    1
2     1
7     0
38    1
Name: res, dtype: int64

In [10]:
m=model.predict(X_test)

In [11]:
model.predict_proba(X_test[:10])

array([[0.53, 0.47],
       [0.47, 0.53],
       [0.68, 0.32],
       [0.79, 0.21],
       [0.19, 0.81],
       [0.32, 0.68],
       [0.89, 0.11],
       [0.84, 0.16],
       [0.43, 0.57],
       [0.97, 0.03]])

In [12]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, m))

Accuracy: 0.7931034482758621


In [13]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=100),X_train, y_train, cv=5)

array([0.64285714, 0.71428571, 0.92307692, 0.76923077, 0.84615385])

In [16]:
dm = pd.read_csv('Bowller_Current - Copy.csv')

In [20]:
p=dm.drop(['res','Player','Span','rating'],axis='columns')

In [21]:
dm.head(10)

Player       Span  Mat  Inns   Overs  Mdns  Runs  Wkts    Ave  \
0           Abu Jayed  2019-2019    2     2    18.0     0   114     5  22.80   
1        Afif Hossain  2020-2020    1     1     2.0     0    12     1  12.00   
2     Al-Amin Hossain  2014-2020   15    15   110.3     7   608    22  27.63   
3         Mahmudullah  2007-2020  188   136   688.4    14  3561    76  46.85   
4    Mashrafe Mortaza  2001-2020  218   218  1804.3   122  8785   269  32.65   
5  Mehidy Hasan Miraz  2017-2020   41    40   349.1    10  1625    40  40.62   
6  Mohammad Saifuddin  2017-2020   22    22   165.3     7   972    31  31.35   
7    Mosaddek Hossain  2016-2019   35    33   150.2     1   787    14  56.21   
8   Mustafizur Rahman  2015-2020   58    57   480.5    22  2512   109  23.04   
9       Rubel Hossain  2009-2019  101    99   756.4    28  4300   126  34.12   

   Econ    SR  4  5  Ct  St     rating  res  
0  6.33  21.6  0  1   0   0  59.543860    1  
1  6.00  12.0  0  0   0   0  13.083333    0  
2  5.50  30.1  2  0   1   0  42.099647    1  
3  5.17  54.3  0  0  64   0  26.784326    0  
4  4.86  40.2  7  1  61   0  41.630347    1  
5  4.65  52.3  1  0  13   0  41.678260    1  
6  5.87  32.0  1  0   3   0  45.665149    1  
7  5.23  64.4  0  0  13   0  24.297174    0  
8  5.22  26.4  3  5  12   0  46.071634    1  
9  5.68  36.0  7  1  20   0  44.773390    1

In [22]:
model.predict(p[:10])

array([1, 0, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [26]:
s=dm.sort_values(by='rating', ascending=False)

In [27]:
s.head(6)

Player       Span  Mat  Inns  Overs  Mdns  Runs  Wkts    Ave  \
0            Abu Jayed  2019-2019    2     2   18.0     0   114     5  22.80   
8    Mustafizur Rahman  2015-2020   58    57  480.5    22  2512   109  23.04   
6   Mohammad Saifuddin  2017-2020   22    22  165.3     7   972    31  31.35   
9        Rubel Hossain  2009-2019  101    99  756.4    28  4300   126  34.12   
11       Shafiul Islam  2010-2020   60    60  423.2    26  2529    70  36.12   
2      Al-Amin Hossain  2014-2020   15    15  110.3     7   608    22  27.63   

    Econ    SR  4  5  Ct  St     rating  res  
0   6.33  21.6  0  1   0   0  59.543860    1  
8   5.22  26.4  3  5  12   0  46.071634    1  
6   5.87  32.0  1  0   3   0  45.665149    1  
9   5.68  36.0  7  1  20   0  44.773390    1  
11  5.97  36.2  4  0   8   0  43.405782    1  
2   5.50  30.1  2  0   1   0  42.099647    1

In [28]:
k=s.Player

In [29]:
k.head(6)

0              Abu Jayed
8      Mustafizur Rahman
6     Mohammad Saifuddin
9          Rubel Hossain
11         Shafiul Islam
2        Al-Amin Hossain
Name: Player, dtype: object